### ISSUE TITLE
3.02 unbootable VM or live DVD

### ISSUE THREAD

**Issue by cblknittights** [brightflash64/Skywave-Linux#1]
Trying to test out V3.02, and when I setup a VBOX VM with the ISO, it takes 10+ minutes to get to a blank black screen. 

Using a LIVE DVD takes 10+ minutes to boot, and then stops at a tty login screen. Lots of sitting and waiting for systemd to start stuff that just keeps repeating 8 minutes+ on one step alone!

This a brand new Dell  3655 8GB RAM quad core AMD processor running Kubuntu 16.04.3

ISO MD5SUM verifies.

V3.01 will eventually boot in a VM 10+ minutes, and boot to the desktop.

VM is 2 CPU 2GB USB Enabled, 3D Enabled. Linux host, I don't speak winslobber. Runs KUbuntu 16.04.3

**Comment by brightflash64** [comment]
That's s prime issue getting attention for Skywave Linux 3.1; hope to have a new ISO out in a couple of weeks.  The goal is set at "ISO size no more than 2 GB and one minute to the desktop."

One more question: how is boot behavior with the ISO dd copied or extracted to a USB flashdrive?

**Comment by brightflash64** [comment]
Removed and reinstalled xserver and associated display drivers, debloated the whole system, and reduced number of autostarting processes.  3.1.0 Boots quickly using either grub or isolinux / syslinux.

**Comment by cblknittights** [comment]
>The goal is set at "ISO size no more than 2 GB and one minute to the desktop."

I am not really concerned with ISO size, I would prefer that as much and as current at the time SDR stuff is crammed in, all the way to 4GB of a DVD. Leaving out things like office software, browsers, email clients,etc. is fine with me. These are easily added by the users with sudo apt-get install 


>One more question: how is boot behavior with the ISO dd copied or extracted to a USB flashdrive?

While I see you have a new ISO, I will try it if I can find a USB drive to use. DVD's are plentiful here, whereas USB sticks are like hens teeth, don't have many of them. Any special dd command??? Some ISO's seem to need special bs etc...
